sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.7
      dist: xenial
      env:
        - TOXENV=coverage
install: pip install tox-travis
script: tox

jobs:
  include:
    - stage: Deploy to Pypi
      deploy:
        - provider: script
          script: python setup.py sdist bdist_wheel && python -m twine upload -u ricardobchaves6 -p $PYPIPASSWORD dist/*
          skip_cleanup: true
          on:
            branch: develop