sudo: false
language: python
dist: xenial
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install: pip install tox-travis
script: tox
jobs:
  include:
    - stage: Coverage
      python:
          - "3.7"
      env:
        - TOXENV=coverage
    - stage: Deploy to Pypi
      python:
          - "3.7"
      env:
        - TOXENV=django21
      deploy:
        provider: pypi
        user: jsmpypi
        password: $PYPIPASSWORD
        on:
          branch: master
        distributions: sdist bdist_wheel
        if: branch = master
    - stage: Deploy to Pypi Test Server
      python:
          - "3.7"
      env:
        - TOXENV=django21
      deploy:
        provider: pypi
        user: jsmpypi
        password: $PYPIPASSWORD
        on:
          branch: develop
        distributions: sdist bdist_wheel
        server: https://test.pypi.org/legacy/
        if: branch = develop