sudo: false
language: python
dist: xenial
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install: pip install tox-travis
script: tox
jobs:
  include:
    - stage: Deploy to Pypi
      deploy:
        provider: pypi
        user: jsmpypi
        password: $PYPIPASSWORD
        on:
          branch: test-travis
        distributions: sdist bdist_wheel
        env:
          - TOXENV=django21


